<?php
/**
 * Handles script and style enqueueing for both the frontend and the block editor.
 *
 * @package Content_Flow_Analytics
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class CFA_Enqueue
 *
 * Loads the frontend tracker script on single post pages and the Gutenberg
 * sidebar panel inside the block editor.
 */
class CFA_Enqueue {

	/**
	 * Enqueues the frontend tracking script on single post/page views.
	 *
	 * The script is only loaded when:
	 *   – The current page is a singular post (any post type).
	 *   – The global $post object is available and has a valid ID.
	 *
	 * Localised data (cfaData) provides the tracker with the REST endpoint URL,
	 * a nonce for (optional) authenticated requests, and the current post ID.
	 *
	 * @return void
	 */
	public static function enqueue_frontend() {
		if ( ! is_singular() ) {
			return;
		}

		$post_id = get_the_ID();
		if ( ! $post_id ) {
			return;
		}

		wp_enqueue_script(
			'cfa-tracker',
			CFA_PLUGIN_URL . 'assets/js/tracker.js',
			array(),
			CFA_VERSION,
			true
		);

		wp_localize_script(
			'cfa-tracker',
			'cfaData',
			array(
				'restUrl'  => esc_url_raw( rest_url( 'content-flow-analytics/v1/track' ) ),
				'nonce'    => wp_create_nonce( 'wp_rest' ),
				'postId'   => $post_id,
			)
		);
	}

	/**
	 * Enqueues the compiled Gutenberg sidebar bundle inside the block editor.
	 *
	 * Expects a compiled `index.js` at `assets/build/index.js` (produced by
	 * `npm run build` via the bundler defined in webpack.config.js).
	 *
	 * An optional `index.asset.php` file (generated by @wordpress/dependency-
	 * extraction-webpack-plugin) is loaded when present so that WordPress can
	 * manage versioning and dependency resolution automatically.
	 *
	 * @return void
	 */
	public static function enqueue_block_editor() {
		$asset_file = CFA_PLUGIN_DIR . 'assets/build/index.asset.php';
		$asset      = file_exists( $asset_file )
			? require $asset_file
			: array(
				'dependencies' => array( 'wp-plugins', 'wp-editor', 'wp-element', 'wp-data', 'wp-components', 'wp-i18n' ),
				'version'      => CFA_VERSION,
			);

		wp_enqueue_script(
			'cfa-block-editor',
			CFA_PLUGIN_URL . 'assets/build/index.js',
			$asset['dependencies'],
			$asset['version'],
			true
		);

		wp_localize_script(
			'cfa-block-editor',
			'cfaEditorData',
			array(
				'statsUrl' => esc_url_raw( rest_url( 'content-flow-analytics/v1/stats' ) ),
				'nonce'    => wp_create_nonce( 'wp_rest' ),
			)
		);

		if ( file_exists( CFA_PLUGIN_DIR . 'assets/build/index.css' ) ) {
			wp_enqueue_style(
				'cfa-block-editor',
				CFA_PLUGIN_URL . 'assets/build/index.css',
				array( 'wp-components' ),
				$asset['version']
			);
		}
	}
}
